---
# Handlers for common role

- name: restart docker
  service:
    name: docker
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart ufw
  service:
    name: ufw
    state: restarted