services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    env_file:
      - .env.docker
    depends_on:
      - redis
      - postgres
      - vector_store
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    env_file:
      - .env.docker
    depends_on:
      - redis
      - postgres
      - vector_store
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=thea
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vector_store:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - vector_store_data:/chroma/data

volumes:
  postgres_data:
  vector_store_data:

networks:
  default:
    external: true
    name: thea-network