version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NODE_BACKEND_URL=http://nodejs-backend:3000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
      - NODE_BACKEND_URL=http://nodejs-backend:3000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  default:
    external: true
    name: thea-network